### ISSUE TITLE
some help needed

### ISSUE THREAD

**Issue by ni-be** [guntherwullaert/asp-language-server#2]
I got the LSP kind of running in Helix (https://helix-editor.com/) which has built in Treesitter and LSP support 

I am running fedora 37, and I got the LSP kind of running by cargo install  git 'repo url'  and adding the  asp-language-server to my editor config. No completions, hints etc.  the only thing it shows me right now is that everything safe or unsafe. 

Before that I downloaded the repo and followed your instructions, but while it finished compiling no executable was created locally, or I am seriously dumb. Building the repo did not create any binaries with which my editor could interact. 

maybe , or rather most likely I did something wrong but a little help on this would be awesome.

**Comment by guntherwullaert** [comment]
Can you check if you are running `cargo build` or `cargo build --release` from the project root directory? 
The normal output directory would be the `target\debug` or `target\release` respectively for the binary files

**Comment by ni-be** [comment]
@guntherwullaert  I will just add images of my out put

This is after I have done both pnpm i and cargo build
![Screenshot from 2023-01-27 15-37-33](https://user-images.githubusercontent.com/10530873/215112978-34e69dc6-78f0-488d-8df7-2cc33a3f0ba4.png)

This is the final output from cargo build : 

![Screenshot from 2023-01-27 15-40-45](https://user-images.githubusercontent.com/10530873/215113368-1b6fad0c-13d1-4a7c-ba75-23554372812a.png)

and finally this is the npm i output ,.. 3 packages were not funded 
![Screenshot from 2023-01-27 15-42-03](https://user-images.githubusercontent.com/10530873/215113591-30b80181-5eb0-4b67-80e3-bd76b0b60505.png)

**Comment by ni-be** [comment]
Ok I changed the path no to the debug repo and in the editor health check it recognizes it 

![image](https://user-images.githubusercontent.com/10530873/215114941-39ec4784-bb14-4572-9abf-780f0dc76765.png)

**Comment by guntherwullaert** [comment]
That file you highlighted is the correct binary file. Do note that the language server and the client tell eachother their capabilities.
This is what the server tells the client, it wants the file changes incrementaly, provides completions and provides definition and references. Ensure that your editor supports those capabilities or check if you need to configure them on the editor side.
```
text_document_sync: Some(TextDocumentSyncCapability::Kind(
    TextDocumentSyncKind::INCREMENTAL,
)),
completion_provider: Some(CompletionOptions {
    resolve_provider: Some(false),
    trigger_characters: Some(vec!["#".to_string()]),
    work_done_progress_options: Default::default(),
    all_commit_characters: None,
}),
definition_provider: Some(OneOf::Left(true)),
references_provider: Some(OneOf::Left(true)),
workspace: Some(WorkspaceServerCapabilities {
    workspace_folders: Some(WorkspaceFoldersServerCapabilities {
        supported: Some(true),
        change_notifications: Some(OneOf::Left(true)),
    }),
    file_operations: None,
}),
..ServerCapabilities::default()
```

Can you also send me a link to what you are using as a template for this ? I am wondering what it wants to have under th econfigured language server option.

**Comment by guntherwullaert** [comment]
I will have a look later but it seems the editor requires a config of the language as that option, you can read more here: https://docs.helix-editor.com/languages.html#language-server-configuration

**Comment by ni-be** [comment]
There is something , thing is though got 0 clue how this LSP or any LSP is constructed.  

This my current Clingo config :  
![Screenshot from 2023-01-27 19-45-01](https://user-images.githubusercontent.com/10530873/215169403-73e9726b-bd8e-4c2f-af2e-a2de805e5aa5.png)

under roots I might need to add Cargo.lock ( but debug/Cargo.lock is empty). 

did some tests, tried to use as grammar source 
'asp-language-server/target/debug/build/tree-sitter-clingo-8f348817d96ee120"'

**Comment by guntherwullaert** [comment]
Ok so I think it's working, I am not sure because it took me already ages to find how to type in the editor. (c for anyone who wants to know) :D. But this is my current configuration:
```toml
[[language]]
name = "clingo"
scope = "scope.clingo"
file-types = ["lp"]
comment-token = "%"
roots = []
indent = { tab-width = 2, unit = "  "}
language-server = { command = "asp-language-server", args = ["--stdio"]}
```

So this should be exactly what you are using, only that I used a path variable leading to the binary and used the arguments to use the stdio pipe. Which was recommended by helix in their docs.´

At least I was obtaining syntax errors and safety was being checked. How to find a definition and find references I don't know.
However I found why code completion is not working:
https://github.com/helix-editor/helix/issues/4962

It seems like helix does not support snippets. While my code completion uses snippets for nearly everything. Therefore the editor does not use that capability. What you could do is changing the helix return of capabilities to true for snippets like mentioned but that is a very hacky way. But it seems for now you will have to wait for helix to implement snippets before you will be able to use code completion. The nice thing though is that safety should already be a really nice addition :)

**Comment by ni-be** [comment]
Awesome thanks,
syntax errors  and safety checks were already working. 
But that explains it , regarding the snippets.  ... I have some snippets that I have to include in some hacky way ( still faster than typing). 

Thanks a lot for your help and time.  Next week I am gonna test it in my back up editor. NeoVim. 

by the way don't you have to type 'i' to switch into the input mode on helix/vim/neovim ?  With 'c' you delete the current selection and enter the insert mode.  SO technically the same but in case you have nothing selected. 

If I get it working, you want to have the config ? Maybe it is a good idea to collect the configs so others can than later just copy and paste? @guntherwullaert

**Comment by guntherwullaert** [comment]
I will add the current config to the readme, feel free to send a pull request to update that readme in case you find a better config :)
